### PR TITLE
#98 php 7

### LINKED ISSUE #7: Multiple VCards in one file
Any specific reason for no support for this??

### PR DESCRIPTION
**Pull request by to-be-the-best**
#98 also fixes  #7 #24.

Intended for a major version update.

Any further suggestions?

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
Hi @to-be-the-best,
Thanks for your PR.
I find it great that you want to help improve the vcard functionality.
Recently I started a new branch with a major update (php 7, new class file structure, ...). You can check it here: https://github.com/jeroendesloovere/vcard/tree/new-version, it seems that you implemented some of the things that I wanted to implement. But my solution seems to go that extra step further by separating Address/Name/... classes and VcfFormatter, ...

Can you take a look at that new branch and tell me what you find of it?

**Comment by jeroendesloovere** [comment]
It's a WIP where the VcfFormatter is working with name and address (other properties are still yet to be programmed). I'm also using the vcard 4.* version.

**Comment by to-be-the-best** [comment]
It looks like a good start.
I think the part of different formatters is an excellent idea.
However, I miss the two-way part of vcard to php and vice versa.
Furthermore, I would have liked, as I did, that input from the php to vcard is the same as the output of the vcard to php.
I also like the fact that the vcard class used as input and output in my version can easily be used in an IDE such as PhpStorm.
My preference would be a mixture of both branches.

**Comment by jeroendesloovere** [comment]
Hi @to-be-the-best, thanks for your reply.
Two-way is the way I want to go! `Formatter <-> Parser`.
Here is the new WIP `test` file - https://github.com/jeroendesloovere/vcard/blob/new-version/tests/VCardTest.php

---
What are you using `coke` for?

**Comment by to-be-the-best** [comment]
I use https://github.com/M6Web/Coke to keep the code style at the right level.
I use the symfony code style both at home and at work.
Unfortunately, the code style checker from scrutinizer can not be set with the correct settings for the symfony code style.
That is why I use coke, which is also used at work.

**Comment by jeroendesloovere** [comment]
Hi @to-be-the-best 

As you know, we are working on a new version...
So closing this PR seems justified, because you made so much changes in here, I'm unable to merge them in the current master version.

Would be nice if you can still help me to build and complete the new vCard version.

**Pull request closed without merging**
