### PR TITLE
Support for adding logos 

### PR DESCRIPTION
**Pull request by wadmiraal**
There is a method for adding a photo, but not for a logo yet. Added it, along with a unit test.

### CODE REVIEW

**Comment by wadmiraal** [comment]
Bump...

Added logo parsing as well, along with new unit tests.

This would be a very handy functionality.

**Comment by wadmiraal** [comment]
Bumping this again. This is the only reason I still have to maintain educach/vcard. The code is simple enough, and unit-tested. Would be very cool if we can add this to the main lib.

**Comment by jeroendesloovere** [comment]
Hi @wadmiraal, thanks for coming back to me.
You know how that goes in vacation periods :-D
I'll take a closer look.

**Comment by wadmiraal** [comment]
Indeed, didn't want to stress you :-). Excellent, thank you!

**Pull request merged**
