### PR TITLE
Multiple VCard

### PR DESCRIPTION
**Pull request by rukandax**
You can generate multiple vcard by adding `new` method between each vcard.

What changes :

- Add `new` method
- `getProperties` method for getting properties from all contacts
- `getProperty` method for getting properties from each contact, you can also getting properties from specific index using parameter

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
Hi @rukandax,
I really appreciate you have taken the time to create a PR for our VCard library.

Could you rename the method `new` to `createNewVCard()`, because `new` causes problems at it is a reserved method name.

**Comment by jeroendesloovere** [comment]
Would be nice if you can fix the PR asap, so I can release a new version 1.6.0 with this in it.
Thanks in advance.

Note: I'm creating a new VCard step by step that has multiple VCards build right in.
You can check the Work In Progress in the [`new-version` branch](https://github.com/jeroendesloovere/vcard/tree/new-version)

**Comment by NMonst4** [comment]
Hi, need this pr is there another solution or should i use rukandax repo?

**Comment by jeroendesloovere** [comment]
Currently there is no released solution.

**Pull request closed without merging**
