### PR TITLE
visit card always has a file name, fixes #76

### LINKED ISSUE #76: visit card with only email address gets no filename (edge case)
When I create a visit card with almost no data (only email address in my example), then filename is empty. On downloading, this resulted in a file named "vcf". (No idea where the leading . (point) was lost.)

This case could be handled in getHeaders (and maybe save and buildVCalendar). I propose a flag to getFileName. When this is set, then 'someone' is returned instead of an empty string.

This is really an edge case. But I was irritated when I got a file without any file extension.

### PR DESCRIPTION
**Pull request by SimonHeimberg**

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
Hi @SimonHeimberg,

I suggest just changing function getFilename()

if ($this->filename == null) {
   return 'unknown';
}

**Comment by SimonHeimberg** [comment]
Nothing against simplifying.
But this minimal change would break "$this->getFilename() === null" in addCompany(). Should this be replaced by "$this->filename === null".
It could break external callers of getFilename(). But I doubt and am ok with this.

How shal I update the changes? Push a 2nd changeset to the current branch?

**Comment by jeroendesloovere** [comment]
Hi, I've looked into it and the `getFilename()` in addCompany can be replaced by if ($this->filename === null).
And the getFilename should get no variable.
Can you change things?

**Comment by jeroendesloovere** [comment]
Hi @SimonHeimberg 
Can you adjust your PR like I mentioned above?

**Comment by SimonHeimberg** [comment]
How shall I update the changes? Push a 2nd commit to the current branch?

Sorry for the delay, I have been away.

**Comment by jeroendesloovere** [comment]
Yes, a second commit will do fine, thanks.

**Comment by SimonHeimberg** [comment]
done

**Pull request merged**
