### PR TITLE
Remove PHP 8 deprecation notice

### PR DESCRIPTION
**Pull request by stephanvierkant**
Fixes 'Required parameter $element follows optional parameter $include' warning.

### CODE REVIEW

**Comment by LordSimal** [comment]
Would love to see this merged.

Sure it would break some implementations where the order of these parameters is already in use with the "old" order but still this is necessary for PHP 8.0 compatibility.

**Comment by stephanvierkant** [comment]
> Sure it would break some implementations where the order of these parameters is already in use with the "old" order but still this is necessary for PHP 8.0 compatibility.

I only changed a private method, so this is not a breaking change.

**Comment by LordSimal** [comment]
Ah right, I overlooked that 😅 
So yeah, this PR will then actually fix the PHP 8 deprecation error.

**Comment by stephanvierkant** [comment]
Ping @jeroendesloovere

**Comment by jakublacko-sorelio** [comment]
@jeroendesloovere Can you please merge this pull request as soon as possible?

**Comment by LordSimal** [comment]
*chirping crickets*

**Comment by sebastiansulinski** [comment]
Such shame - I'll have to look at alternatives as it looks chances are slim for this to get merged.

**Comment by LordSimal** [comment]
I forked this repo and applied the changes from this PR.
https://github.com/LordSimal/vcard

**Comment by LordSimal** [comment]
The fact that Scrutinizer fails here is the fact, that a very old version of PHPCS is used with PHP 7.3
image

Thats why this PR can't be merged I would guess. But the fact that the Scrutinizer setup is not "publicly" available and therefore not in our hands to adjust/improve we can't help @jeroendesloovere to fix this.

I would rather suggest him to switch to Github Actions because these are built upon YAML Files which are also committed in the repo and therefore the community can help improve the auto-testing setup as well.

**Comment by stephanvierkant** [comment]
Friendly ping to @jeroendesloovere

**Comment by jeroendesloovere** [comment]
Hi guys, Sorry I got back to you so late, got my github notifications disabled and therefor did not saw all the commotion here.

I'm definitely merging this shizzle in!
Thanks a lot!

**Pull request merged**
